apiVersion: v1
kind: Service
metadata:
  name: nodebackend
spec:
  type: NodePort
  selector:
    app: component-nodebackend
  ports:
  - port: 9096
    targetPort: 9096
    nodePort: 31001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodebackend
spec:
  selector:
    matchLabels:
      app: component-nodebackend
  template:
    metadata:
      labels:
        app: component-nodebackend
    spec:
      containers:
      - name: node-backend
        image: tobespc/nodebackend
        imagePullPolicy: Always
        ports:
        - containerPort: 9096